apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: db
  name: mongo
spec: 
  type: ClusterIP
  ports: 
  - name: db
    port: 8081
    targetPort: 27017
  selector: 
    name: db-application